import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  // ---------- Africa ----------
  { code: "DZ", name: "Algeria", capital: "Algiers", continent: "Africa" },
  { code: "AO", name: "Angola", capital: "Luanda", continent: "Africa" },
  { code: "BJ", name: "Benin", capital: "Porto-Novo", continent: "Africa" },
  { code: "BW", name: "Botswana", capital: "Gaborone", continent: "Africa" },
  { code: "BF", name: "Burkina Faso", capital: "Ouagadougou", continent: "Africa" },
  { code: "BI", name: "Burundi", capital: "Gitega", continent: "Africa" },
  { code: "CV", name: "Cabo Verde", capital: "Praia", continent: "Africa" },
  { code: "CM", name: "Cameroon", capital: "Yaoundé", continent: "Africa" },
  { code: "CF", name: "Central African Republic", capital: "Bangui", continent: "Africa" },
  { code: "TD", name: "Chad", capital: "N'Djamena", continent: "Africa" },
  { code: "KM", name: "Comoros", capital: "Moroni", continent: "Africa" },
  { code: "CD", name: "DR Congo", capital: "Kinshasa", continent: "Africa" },
  { code: "CG", name: "Republic of the Congo", capital: "Brazzaville", continent: "Africa" },
  { code: "DJ", name: "Djibouti", capital: "Djibouti", continent: "Africa" },
  { code: "EG", name: "Egypt", capital: "Cairo", continent: "Africa" },
  { code: "GQ", name: "Equatorial Guinea", capital: "Malabo", continent: "Africa" },
  { code: "ER", name: "Eritrea", capital: "Asmara", continent: "Africa" },
  { code: "SZ", name: "Eswatini", capital: "Mbabane", continent: "Africa" },
  { code: "ET", name: "Ethiopia", capital: "Addis Ababa", continent: "Africa" },
  { code: "GA", name: "Gabon", capital: "Libreville", continent: "Africa" },
  { code: "GM", name: "Gambia", capital: "Banjul", continent: "Africa" },
  { code: "GH", name: "Ghana", capital: "Accra", continent: "Africa" },
  { code: "GN", name: "Guinea", capital: "Conakry", continent: "Africa" },
  { code: "GW", name: "Guinea-Bissau", capital: "Bissau", continent: "Africa" },
  { code: "CI", name: "Ivory Coast", capital: "Yamoussoukro", continent: "Africa" },
  { code: "KE", name: "Kenya", capital: "Nairobi", continent: "Africa" },
  { code: "LS", name: "Lesotho", capital: "Maseru", continent: "Africa" },
  { code: "LR", name: "Liberia", capital: "Monrovia", continent: "Africa" },
  { code: "LY", name: "Libya", capital: "Tripoli", continent: "Africa" },
  { code: "MG", name: "Madagascar", capital: "Antananarivo", continent: "Africa" },
  { code: "MW", name: "Malawi", capital: "Lilongwe", continent: "Africa" },
  { code: "ML", name: "Mali", capital: "Bamako", continent: "Africa" },
  { code: "MR", name: "Mauritania", capital: "Nouakchott", continent: "Africa" },
  { code: "MU", name: "Mauritius", capital: "Port Louis", continent: "Africa" },
  { code: "MA", name: "Morocco", capital: "Rabat", continent: "Africa" },
  { code: "MZ", name: "Mozambique", capital: "Maputo", continent: "Africa" },
  { code: "NA", name: "Namibia", capital: "Windhoek", continent: "Africa" },
  { code: "NE", name: "Niger", capital: "Niamey", continent: "Africa" },
  { code: "NG", name: "Nigeria", capital: "Abuja", continent: "Africa" },
  { code: "RW", name: "Rwanda", capital: "Kigali", continent: "Africa" },
  { code: "ST", name: "Sao Tome and Principe", capital: "São Tomé", continent: "Africa" },
  { code: "SN", name: "Senegal", capital: "Dakar", continent: "Africa" },
  { code: "SC", name: "Seychelles", capital: "Victoria", continent: "Africa" },
  { code: "SL", name: "Sierra Leone", capital: "Freetown", continent: "Africa" },
  { code: "SO", name: "Somalia", capital: "Mogadishu", continent: "Africa" },
  { code: "ZA", name: "South Africa", capital: "Pretoria", continent: "Africa" },
  { code: "SS", name: "South Sudan", capital: "Juba", continent: "Africa" },
  { code: "SD", name: "Sudan", capital: "Khartoum", continent: "Africa" },
  { code: "TZ", name: "Tanzania", capital: "Dodoma", continent: "Africa" },
  { code: "TG", name: "Togo", capital: "Lomé", continent: "Africa" },
  { code: "TN", name: "Tunisia", capital: "Tunis", continent: "Africa" },
  { code: "UG", name: "Uganda", capital: "Kampala", continent: "Africa" },
  { code: "ZM", name: "Zambia", capital: "Lusaka", continent: "Africa" },
  { code: "ZW", name: "Zimbabwe", capital: "Harare", continent: "Africa" },

  // ---------- Asia ----------
  { code: "AF", name: "Afghanistan", capital: "Kabul", continent: "Asia" },
  { code: "AM", name: "Armenia", capital: "Yerevan", continent: "Asia" },
  { code: "AZ", name: "Azerbaijan", capital: "Baku", continent: "Asia" },
  { code: "BH", name: "Bahrain", capital: "Manama", continent: "Asia" },
  { code: "BD", name: "Bangladesh", capital: "Dhaka", continent: "Asia" },
  { code: "BT", name: "Bhutan", capital: "Thimphu", continent: "Asia" },
  { code: "BN", name: "Brunei", capital: "Bandar Seri Begawan", continent: "Asia" },
  { code: "KH", name: "Cambodia", capital: "Phnom Penh", continent: "Asia" },
  { code: "CN", name: "China", capital: "Beijing", continent: "Asia" },
  { code: "CY", name: "Cyprus", capital: "Nicosia", continent: "Asia" },
  { code: "GE", name: "Georgia", capital: "Tbilisi", continent: "Asia" },
  { code: "IN", name: "India", capital: "New Delhi", continent: "Asia" },
  { code: "ID", name: "Indonesia", capital: "Jakarta", continent: "Asia" },
  { code: "IR", name: "Iran", capital: "Tehran", continent: "Asia" },
  { code: "IQ", name: "Iraq", capital: "Baghdad", continent: "Asia" },
  { code: "IL", name: "Israel", capital: "Jerusalem", continent: "Asia" },
  { code: "JP", name: "Japan", capital: "Tokyo", continent: "Asia" },
  { code: "JO", name: "Jordan", capital: "Amman", continent: "Asia" },
  { code: "KZ", name: "Kazakhstan", capital: "Astana", continent: "Asia" },
  { code: "KW", name: "Kuwait", capital: "Kuwait City", continent: "Asia" },
  { code: "KG", name: "Kyrgyzstan", capital: "Bishkek", continent: "Asia" },
  { code: "LA", name: "Laos", capital: "Vientiane", continent: "Asia" },
  { code: "LB", name: "Lebanon", capital: "Beirut", continent: "Asia" },
  { code: "MY", name: "Malaysia", capital: "Kuala Lumpur", continent: "Asia" },
  { code: "MV", name: "Maldives", capital: "Malé", continent: "Asia" },
  { code: "MN", name: "Mongolia", capital: "Ulaanbaatar", continent: "Asia" },
  { code: "MM", name: "Myanmar", capital: "Naypyidaw", continent: "Asia" },
  { code: "NP", name: "Nepal", capital: "Kathmandu", continent: "Asia" },
  { code: "KP", name: "North Korea", capital: "Pyongyang", continent: "Asia" },
  { code: "OM", name: "Oman", capital: "Muscat", continent: "Asia" },
  { code: "PK", name: "Pakistan", capital: "Islamabad", continent: "Asia" },
  { code: "PS", name: "Palestine", capital: "Ramallah", continent: "Asia" },
  { code: "PH", name: "Philippines", capital: "Manila", continent: "Asia" },
  { code: "QA", name: "Qatar", capital: "Doha", continent: "Asia" },
  { code: "SA", name: "Saudi Arabia", capital: "Riyadh", continent: "Asia" },
  { code: "SG", name: "Singapore", capital: "Singapore", continent: "Asia" },
  { code: "KR", name: "South Korea", capital: "Seoul", continent: "Asia" },
  { code: "LK", name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: "Asia" },
  { code: "SY", name: "Syria", capital: "Damascus", continent: "Asia" },
  { code: "TW", name: "Taiwan", capital: "Taipei", continent: "Asia" },
  { code: "TJ", name: "Tajikistan", capital: "Dushanbe", continent: "Asia" },
  { code: "TH", name: "Thailand", capital: "Bangkok", continent: "Asia" },
  { code: "TL", name: "Timor-Leste", capital: "Dili", continent: "Asia" },
  { code: "TR", name: "Turkey", capital: "Ankara", continent: "Asia" },
  { code: "TM", name: "Turkmenistan", capital: "Ashgabat", continent: "Asia" },
  { code: "AE", name: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia" },
  { code: "UZ", name: "Uzbekistan", capital: "Tashkent", continent: "Asia" },
  { code: "VN", name: "Vietnam", capital: "Hanoi", continent: "Asia" },
  { code: "YE", name: "Yemen", capital: "Sana'a", continent: "Asia" },

  // ---------- Europe ----------
  { code: "AL", name: "Albania", capital: "Tirana", continent: "Europe" },
  { code: "AD", name: "Andorra", capital: "Andorra la Vella", continent: "Europe" },
  { code: "AT", name: "Austria", capital: "Vienna", continent: "Europe" },
  { code: "BY", name: "Belarus", capital: "Minsk", continent: "Europe" },
  { code: "BE", name: "Belgium", capital: "Brussels", continent: "Europe" },
  { code: "BA", name: "Bosnia and Herzegovina", capital: "Sarajevo", continent: "Europe" },
  { code: "BG", name: "Bulgaria", capital: "Sofia", continent: "Europe" },
  { code: "HR", name: "Croatia", capital: "Zagreb", continent: "Europe" },
  { code: "CZ", name: "Czech Republic", capital: "Prague", continent: "Europe" },
  { code: "DK", name: "Denmark", capital: "Copenhagen", continent: "Europe" },
  { code: "EE", name: "Estonia", capital: "Tallinn", continent: "Europe" },
  { code: "FI", name: "Finland", capital: "Helsinki", continent: "Europe" },
  { code: "FR", name: "France", capital: "Paris", continent: "Europe" },
  { code: "DE", name: "Germany", capital: "Berlin", continent: "Europe" },
  { code: "GR", name: "Greece", capital: "Athens", continent: "Europe" },
  { code: "HU", name: "Hungary", capital: "Budapest", continent: "Europe" },
  { code: "IS", name: "Iceland", capital: "Reykjavik", continent: "Europe" },
  { code: "IE", name: "Ireland", capital: "Dublin", continent: "Europe" },
  { code: "IT", name: "Italy", capital: "Rome", continent: "Europe" },
  { code: "XK", name: "Kosovo", capital: "Pristina", continent: "Europe" },
  { code: "LV", name: "Latvia", capital: "Riga", continent: "Europe" },
  { code: "LI", name: "Liechtenstein", capital: "Vaduz", continent: "Europe" },
  { code: "LT", name: "Lithuania", capital: "Vilnius", continent: "Europe" },
  { code: "LU", name: "Luxembourg", capital: "Luxembourg", continent: "Europe" },
  { code: "MT", name: "Malta", capital: "Valletta", continent: "Europe" },
  { code: "MD", name: "Moldova", capital: "Chisinau", continent: "Europe" },
  { code: "MC", name: "Monaco", capital: "Monaco", continent: "Europe" },
  { code: "ME", name: "Montenegro", capital: "Podgorica", continent: "Europe" },
  { code: "NL", name: "Netherlands", capital: "Amsterdam", continent: "Europe" },
  { code: "MK", name: "North Macedonia", capital: "Skopje", continent: "Europe" },
  { code: "NO", name: "Norway", capital: "Oslo", continent: "Europe" },
  { code: "PL", name: "Poland", capital: "Warsaw", continent: "Europe" },
  { code: "PT", name: "Portugal", capital: "Lisbon", continent: "Europe" },
  { code: "RO", name: "Romania", capital: "Bucharest", continent: "Europe" },
  { code: "RU", name: "Russia", capital: "Moscow", continent: "Europe" },
  { code: "SM", name: "San Marino", capital: "San Marino", continent: "Europe" },
  { code: "RS", name: "Serbia", capital: "Belgrade", continent: "Europe" },
  { code: "SK", name: "Slovakia", capital: "Bratislava", continent: "Europe" },
  { code: "SI", name: "Slovenia", capital: "Ljubljana", continent: "Europe" },
  { code: "ES", name: "Spain", capital: "Madrid", continent: "Europe" },
  { code: "SE", name: "Sweden", capital: "Stockholm", continent: "Europe" },
  { code: "CH", name: "Switzerland", capital: "Bern", continent: "Europe" },
  { code: "UA", name: "Ukraine", capital: "Kyiv", continent: "Europe" },
  { code: "GB", name: "United Kingdom", capital: "London", continent: "Europe" },
  { code: "VA", name: "Vatican City", capital: "Vatican City", continent: "Europe" },

  // ---------- North America ----------
  { code: "AG", name: "Antigua and Barbuda", capital: "Saint John's", continent: "North America" },
  { code: "BS", name: "Bahamas", capital: "Nassau", continent: "North America" },
  { code: "BB", name: "Barbados", capital: "Bridgetown", continent: "North America" },
  { code: "BZ", name: "Belize", capital: "Belmopan", continent: "North America" },
  { code: "CA", name: "Canada", capital: "Ottawa", continent: "North America" },
  { code: "CR", name: "Costa Rica", capital: "San José", continent: "North America" },
  { code: "CU", name: "Cuba", capital: "Havana", continent: "North America" },
  { code: "DM", name: "Dominica", capital: "Roseau", continent: "North America" },
  { code: "DO", name: "Dominican Republic", capital: "Santo Domingo", continent: "North America" },
  { code: "SV", name: "El Salvador", capital: "San Salvador", continent: "North America" },
  { code: "GD", name: "Grenada", capital: "St. George's", continent: "North America" },
  { code: "GT", name: "Guatemala", capital: "Guatemala City", continent: "North America" },
  { code: "HT", name: "Haiti", capital: "Port-au-Prince", continent: "North America" },
  { code: "HN", name: "Honduras", capital: "Tegucigalpa", continent: "North America" },
  { code: "JM", name: "Jamaica", capital: "Kingston", continent: "North America" },
  { code: "MX", name: "Mexico", capital: "Mexico City", continent: "North America" },
  { code: "NI", name: "Nicaragua", capital: "Managua", continent: "North America" },
  { code: "PA", name: "Panama", capital: "Panama City", continent: "North America" },
  { code: "KN", name: "Saint Kitts and Nevis", capital: "Basseterre", continent: "North America" },
  { code: "LC", name: "Saint Lucia", capital: "Castries", continent: "North America" },
  { code: "VC", name: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: "North America" },
  { code: "TT", name: "Trinidad and Tobago", capital: "Port of Spain", continent: "North America" },
  { code: "US", name: "United States", capital: "Washington, D.C.", continent: "North America" },

  // ---------- South America ----------
  { code: "AR", name: "Argentina", capital: "Buenos Aires", continent: "South America" },
  { code: "BO", name: "Bolivia", capital: "Sucre", continent: "South America" },
  { code: "BR", name: "Brazil", capital: "Brasília", continent: "South America" },
  { code: "CL", name: "Chile", capital: "Santiago", continent: "South America" },
  { code: "CO", name: "Colombia", capital: "Bogotá", continent: "South America" },
  { code: "EC", name: "Ecuador", capital: "Quito", continent: "South America" },
  { code: "GY", name: "Guyana", capital: "Georgetown", continent: "South America" },
  { code: "PY", name: "Paraguay", capital: "Asunción", continent: "South America" },
  { code: "PE", name: "Peru", capital: "Lima", continent: "South America" },
  { code: "SR", name: "Suriname", capital: "Paramaribo", continent: "South America" },
  { code: "UY", name: "Uruguay", capital: "Montevideo", continent: "South America" },
  { code: "VE", name: "Venezuela", capital: "Caracas", continent: "South America" },

  // ---------- Oceania ----------
  { code: "AU", name: "Australia", capital: "Canberra", continent: "Oceania" },
  { code: "FJ", name: "Fiji", capital: "Suva", continent: "Oceania" },
  { code: "KI", name: "Kiribati", capital: "Tarawa", continent: "Oceania" },
  { code: "MH", name: "Marshall Islands", capital: "Majuro", continent: "Oceania" },
  { code: "FM", name: "Micronesia", capital: "Palikir", continent: "Oceania" },
  { code: "NR", name: "Nauru", capital: "Yaren", continent: "Oceania" },
  { code: "NZ", name: "New Zealand", capital: "Wellington", continent: "Oceania" },
  { code: "PW", name: "Palau", capital: "Ngerulmud", continent: "Oceania" },
  { code: "PG", name: "Papua New Guinea", capital: "Port Moresby", continent: "Oceania" },
  { code: "WS", name: "Samoa", capital: "Apia", continent: "Oceania" },
  { code: "SB", name: "Solomon Islands", capital: "Honiara", continent: "Oceania" },
  { code: "TO", name: "Tonga", capital: "Nuku'alofa", continent: "Oceania" },
  { code: "TV", name: "Tuvalu", capital: "Funafuti", continent: "Oceania" },
  { code: "VU", name: "Vanuatu", capital: "Port Vila", continent: "Oceania" },
];
